import { ConnectButton, useWallet } from '@simpleweb/open-format-react';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Logo from '../components/logo';
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { isConnected } = useWallet();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Your Next NFT platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Welcome to the Open-Format Starter
        </h1>
        <p>
          <a className={styles.link} href='https://github.com/simpleweb/open-format/tree/main/sdks/react' target="_blank" rel="noopener noreferrer">
          Back to the documentation
          </a>
        </p>

        <p >
          Create Your Next NFT platform
        </p>

        <p>
          No need to build your own connection button we have sorted all that for you, Click below to see how easy it is to connect your wallet!!
        </p>
        

        <div className={styles.grid}>
          <ConnectButton className={styles.button} />        
        </div>
      </main>

      <footer className={styles.footer}>
        <Link href={'https://simpleweb.co.uk'}>
        <a>
        <Logo />
        </a>
        </Link>
      </footer>
    </div>
  )
}

export default Home
